# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0002_auto_20171027_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
